server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hilayapp
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
file:
 upload-dir: /path/to/upload/directory